#!/bin/bash
# Daily Top10 Generator

TOKEN="${OPENNEWS_TOKEN}"
API_URL="https://ai.6551.io/open/news_search"
OUTPUT_DIR="/Users/wangwu/workspace/news-digest/output"
DATE=$(date +%Y-%m-%d)

mkdir -p "$OUTPUT_DIR"

# 抓取当天全部高评分新闻
fetch_daily() {
  curl -s -X POST "$API_URL" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    -d '{
      "limit": 100,
      "page": 1
    }' | jq '[.data[] | select(.aiRating.score >= 50)] | sort_by(.aiRating.score) | reverse | .[0:10]'
}

main() {
  echo "Generating daily Top10 for $DATE..."
  
  TOP10=$(fetch_daily)
  
  # 保存
  echo "$TOP10" > "$OUTPUT_DIR/daily-$DATE.json"
  
  # 生成 markdown 报告
  cat > "$OUTPUT_DIR/daily-$DATE.md" << EOF
# 📰 每日 Top10 - $DATE

| # | 分数 | 来源 | 内容 |
|---|------|------|------|
$(echo "$TOP10" | jq -r '.[] | "| \(.aiRating.score) | \(.newsType) | \(.text[0:60])... |"')

---
Generated by OpenClaw News Digest
EOF
  
  echo "Done! Output: $OUTPUT_DIR/daily-$DATE.json"
}

main
